language: c
sudo: required
dist: trusty

services:
  - docker

env:
  - OS=fedora
  - OS=debian-x86_64
  - OS=arch
  - OS=debian-s390x
  - OS=debian-i386
  - OS=ubuntu-clang

install:
  - ./contrib/ci/generate_docker.py

script:
  - docker run -e OS=$OS -e CI=true -t -v `pwd`/dist:/build/dist fwupd-$OS
