language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t fwupd-fedora-25 -f contrib/ci/Dockerfile-fedora-25 .
  - docker build -t fwupd-debian-experimental -f contrib/ci/Dockerfile-debian-experimental .

script:
  - docker run -t -v `pwd`:/build fwupd-fedora-25 ./contrib/ci/build_and_test.sh
  - docker run -t -v `pwd`:/build fwupd-debian-experimental ./contrib/ci/build_and_test.sh
