name: Create containers
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [fedora, debian-x86_64, arch, debian-i386]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # TODO(#122): Remove step when https://github.com/actions/virtual-environments/issues/2658 fixed
      - name: update runc # https://github.com/actions/virtual-environments/issues/2698#issuecomment-779262068
        if: startsWith(matrix.os, 'arch')
        run: |
          sudo apt-get install --assume-yes libseccomp-dev
          git clone https://github.com/opencontainers/runc
          cd runc && git checkout v1.0.0-rc93 && make -j`nproc` && sudo make install
          cd .. && rm --recursive runc
      - name: "Generate Dockerfile"
        env:
          OS: ${{ matrix.os }}
        run: ./contrib/ci/generate_docker.py
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: fwupd/fwupd/fwupd-${{matrix.os}}
          tags: latest
