name: Create containers
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  push_to_registry:
    permissions:
      packages: write # for docker/build-push-action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [precommit, fedora, debian-x86_64, arch, debian-i386, void]

    steps:
      - name: Check out the repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: "Generate Dockerfile"
        env:
          OS: ${{ matrix.os }}
        run: ./contrib/ci/generate_docker.py
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@c382f710d39a5bb4e430307530a720f50c2d3318 # v6.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/fwupd/fwupd/fwupd-${{matrix.os}}:latest
